### ISSUE TITLE
dest?.writeBoolean

### ISSUE THREAD

**Issue by yankeppey** [nekocode/android-parcelable-intellij-plugin-kotlin#1]
Hey, thanks for your plugin,
but it generates Parcel.writeBoolean method call which simply doesn't exists. Probably, the following approach should be used:

http://stackoverflow.com/questions/6201311/how-to-read-write-a-boolean-when-implementing-the-parcelable-interface

**Comment by nekocode** [comment]
Thanks! I have fixed it.
