### ISSUE TITLE
optional fields

### ISSUE THREAD

**Issue by CapnSpellcheck** [nekocode/android-parcelable-intellij-plugin-kotlin#10]
If the class has optional fields, it might be helpful to use writeValue/readValue calls.
With my optional fields, current plugin generates `source.readString?()` which is invalid, besides if I remove the '?', the function will probably result in NPE if field is null.

**Comment by nekocode** [comment]
Don't declare a nullable field in the primary constructor. If you want to have a optional field, you should better give it a default value. 

```
class Test(val a: Int, val test: String = "")
```

Or you really need a nullable field, you can declare it in the class body. This plugin will not generate `writeValue/readValue` calls for it.

```
class Test2(val a: Int) {
    val b: String? = null
}
```

**Comment by vanniktech** [comment]
@nekocode I'm facing the same problem and in my opinion this generator should be able to handle optionals properly.

Also if I'd do your 'workaround' I'd end up with not having `b` when it has an actual value.

**Comment by nekocode** [comment]
@vanniktech Well, I will fix it this weekend.

**Comment by nekocode** [comment]
Fixed in the new release: https://github.com/nekocode/android-parcelable-intellij-plugin-kotlin/releases/tag/0.6.2

**Comment by CapnSpellcheck** [comment]
@vanniktech is the generator still working for you? I'm using latest Kotlin plugin, 1.1.1 and when I run the Generate command, an IDE error popup appears, and the generated code seems incomplete.
Just curious, because unfortunately I might need to use org.parceler!

**Comment by vanniktech** [comment]
Seems to be generating code that does compile.

**Comment by nekocode** [comment]
The lastest 0.7.0 fixed some issues: https://github.com/nekocode/android-parcelable-intellij-plugin-kotlin/releases/tag/0.7.0
