### ISSUE TITLE
Support Enums

### ISSUE THREAD

**Issue by Jawnnypoo** [nekocode/android-parcelable-intellij-plugin-kotlin#12]
When I try to generate a parcelable class which contains an enum, it generates something like:

```
enum class SortOrder {
    AlphaAscending ,
    AlphaDescending,
    Date
}
```

```
constructor(source: Parcel) : this(source.readSortOrder())

override fun writeToParcel(dest: Parcel?, flags: Int) {
        dest?.writeSortOrder(sortOrder)
    }
```
and cannot resolve those read or write methods. Not sure if this has something to do with my code, or this plugin.

**Comment by Jawnnypoo** [comment]
It should be something more like 

```
out.writeInt(myEnum.ordinal());
```

and 

```
constructor(source: Parcel) : this(MyEnum.values()[source.readInt()])
```

**Comment by nekocode** [comment]
Thank's for the report. Fixed.
https://github.com/nekocode/android-parcelable-intellij-plugin-kotlin/releases/tag/0.6

**Comment by Jawnnypoo** [comment]
Great news, thanks!
