### ISSUE TITLE
No need for dest null check

### ISSUE THREAD

**Issue by Jeevuz** [nekocode/android-parcelable-intellij-plugin-kotlin#17]
Hi! Thanks for the generator!
I think we don't need to check the ```dest``` for null in 
```kotlin
        override fun writeToParcel(dest: Parcel?, flags: Int) {
            dest?.writeInt(orderId)
        }
```
because dest will never be null. 
Check out the Parcelable javadoc and the example in it:
```java
      public void writeToParcel(Parcel out, int flags) {
          out.writeInt(mData);
      }
```
This method not meant to be called with null Parcel.

So I think it will be good for readability to remove this unnecessary null check by set dest as non-null parameter:
```kotlin
        override fun writeToParcel(dest: Parcel, flags: Int) {
            dest.writeInt(orderId)
        }
```

**Comment by nekocode** [comment]
Thanks for you suggestion. You are right. I will remove the unnecessary null check in next release.
