### ISSUE TITLE
Unneded '?' in classLoader declaration

### ISSUE THREAD

**Issue by Jeevuz** [nekocode/android-parcelable-intellij-plugin-kotlin#19]
I have ```val income: Income? ``` property and following code is generated for it
```kotlin
source.readParcelable<Income?>(Income?::class.java.classLoader)
```
As you see the '?' mark in ```Income?::class.java.classLoader``` is not needed. And lint says "type in class literal must not be nullable".

**Comment by Jeevuz** [comment]
You know what? I think ```readParcelable<Income>``` also can be written without '?' because this method just will return null if there was null passed in it. 

From readParcelable javadoc: 
"@return Returns the newly created Parcelable, or null if a null object has been written."

**Comment by nekocode** [comment]
I have resolved all your issues in the lastest release: [0.7.1](https://github.com/nekocode/android-parcelable-intellij-plugin-kotlin/releases/tag/0.7.1)
Thanks for all your suggestions!

**Comment by Jeevuz** [comment]
Great! Thanks for quick fixes ;)
