### ISSUE TITLE
Bad style for generated code for constructor

### ISSUE THREAD

**Issue by danielgomezrico** [nekocode/android-parcelable-intellij-plugin-kotlin#21]
Version: 0.7.1
Android Studio: 2.2.3

Response:
```
constructor(source: Parcel) : this(
  source.readLong(),
  source.readString(),
  source.readString()
  )
```

How it will be better:

```
constructor(source: Parcel) : this(source.readLong(), source.readString(),  source.readString())
```

**Comment by nekocode** [comment]
Thanks for the report. I will check it.

**Comment by danielgomezrico** [comment]
thanks ☺️

**Comment by laminr** [comment]
Hi,
my constructor is generated empty... 
and the writeToParcel as well

constructor(source: Parcel) : this(
)

override fun writeToParcel(dest: Parcel, flags: Int) {}

where that could come from?

**Comment by n-belokopytov** [comment]
@laminr it's because you did not specify the vars in the default constructor in class declaration.

@nekocode for some reason your plugin takes into account only vars that are declared in the default constructor and doesn't see any outstanding vars. IMO it's a bug, since some attributes are not supposed to be a part of the constructor, but are supposed to be preserved through Parcelable.

**Comment by laminr** [comment]
right it works, wonderfull

but, does that mean that it is mandatory to have the default constructor with all the variable to works?

I have an object with 50+ variables, but only need a constuctor with 10 params or a non-arg constructor while using getter/setters after

But for the parcellable thing, I need that all variables is included

What is the best thing to do?

**Comment by n-belokopytov** [comment]
@laminr let's wait @nekocode response - I have the same problem

**Comment by nekocode** [comment]
@laminr You must to specify all the vars in the default constructor now, but you can also leave fields that you don't want to assign values empty in constructor.
ie. 
```java
class A(val a: String, val b: String = "")
```

@n-belokopytov I will release a new version to fix it.

**Comment by laminr** [comment]
Thanks @nekocode
