### ISSUE TITLE
Companion object should be below method declarations

### ISSUE THREAD

**Issue by REggar** [nekocode/android-parcelable-intellij-plugin-kotlin#25]
According to the official style guide the companion object should be below the methods:
https://github.com/JetBrains/kotlin-web-site/blob/636fe9e9d799eaa1e5c9d02b838f45aab1a13af2/pages/docs/reference/coding-conventions.md#class-layout

Its a small change but would you be able to swap the default layout to match this?

**Comment by nekocode** [comment]
Thanks for the suggestion! I will fix it soon.
