### ISSUE TITLE
Plagiarism ?

### ISSUE THREAD

**Issue by rhonyabdullah** [nekocode/android-parcelable-intellij-plugin-kotlin#29]
Hello @nekocode and @xorsk 
I'm just accidentally browse some kotlin plugin through android studio and found that this [man](https://github.com/wznshuai/android-parcelable-intellij-plugin-kotlin) also re-publish your plugin with the same name with yours **Parcelable Code Generator** Hope this information helps both of you.

**Comment by nekocode** [comment]
This project is licensed under Apache 2.0. So his reproduction is legal. However, thank you for your information.
