### ISSUE TITLE
Plugin crashes in Kotlin 1.0.4-release-Studio2.2-22

### ISSUE THREAD

**Issue by shuufi** [nekocode/android-parcelable-intellij-plugin-kotlin#9]
Plugin crashes with error message below when trying to generate

![image](https://cloud.githubusercontent.com/assets/3444352/18793176/265147c2-81ec-11e6-832c-054cbc544851.png)

**Comment by nekocode** [comment]
Thanks for the report. I will fix it soon.

**Comment by nekocode** [comment]
Fixed. Please see the [lastest realease](https://github.com/nekocode/android-parcelable-intellij-plugin-kotlin/releases/latest).
